# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Research
    url: '#recent-work'
    weight: 20
  - name: Experience
    url: '#experience'
    weight: 30
  - name: CV
    url: uploads/Graziul CV 2025_05_12.pdf
    weight: 40
  - name: Resources
    url: '#resources'
    weight: 50

# Resources submenu (if supported by theme)
resources:
  - name: BPC-CPD Corpus
    url: https://voices.uchicago.edu/p2r/bpc-cpd-corpus/
    weight: 10
  - name: ICML 2025 Paper
    url: https://openreview.net/forum?id=1RlrtH6ydW
    weight: 20
  - name: CSCW 2024 Paper
    url: https://dl.acm.org/doi/10.1145/3686921
    weight: 30
  - name: SLT 2024 Paper
    url: https://ieeexplore.ieee.org/document/10832157
    weight: 40
