# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#hero'
    weight: 10
  - name: Foundation
    url: '#foundation'
    weight: 20
  - name: Methods
    url: '#computational'
    weight: 30
  - name: AI & Policing
    url: '#policing'
    weight: 40
  - name: Current Work
    url: '#current'
    weight: 50
  - name: Resources
    url: '#resources'
    weight: 60
  - name: CV
    url: uploads/Graziul CV 2025_05_12.pdf
    weight: 70
